apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mspoc02-demoapp-deployment
spec:
  replicas: 2
  template:
    metadata:
      name: pod-mspoc02-demoapp
      labels:
        run: mspoc02-demoapp
    spec:
      containers:
        - name: mspoc02-demoapp-container
          image: "registry.ng.bluemix.net/hmuralid1/mspoc02_demoapp:1"
          imagePullPolicy: Always
          
---
apiVersion: v1
kind: Service
metadata: 
  labels: 
    run: mspoc02-demoapp
  name: mspoc02-demoapp-service
spec: 
  ports: 
    - 
      nodePort: 30072
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector: 
    run: mspoc02-demoapp
  type: NodePort

